name: build

on:
  push:
    branches:
      - main

jobs:
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # SDK Version to use.

    - run: dotnet publish -c release -r linux-x64 --self-contained
      working-directory: ./dotnet-wtrace

    - run: dotnet publish -c release -r osx-x64 --self-contained
      working-directory: ./dotnet-wtrace

    - run: dotnet publish -c release -r win-x64 --self-contained
      working-directory: ./dotnet-wtrace

    - uses: actions/upload-artifact@main
      with:
        name: dotnet-wtrace-linux
        path: dotnet-wtrace/bin/release/net6.0/linux-x64/publish/dotnet-wtrace.*

    - uses: actions/upload-artifact@main
      with:
        name: dotnet-wtrace-windows
        path: dotnet-wtrace/bin/release/net6.0/win-x64/publish/dotnet-wtrace.*

    - uses: actions/upload-artifact@main
      with:
        name: dotnet-wtrace-osx
        path: dotnet-wtrace/bin/release/net6.0/osx-x64/publish/dotnet-wtrace.*
